# Translations template for PROJECT.
# Copyright (C) 2023 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2023.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2023-03-29 10:33+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.11.0\n"

#: launch_worker.py:48 launch_worker_splitter.py:48
msgid "FILE_UPLOADED"
msgstr ""

#: src/backend/verifier_exports.py:85 src/backend/verifier_exports.py:88
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/verifier_exports.py:154 src/backend/verifier_exports.py:157
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/splitter.py:438
#: src/backend/controllers/splitter.py:444 src/backend/verifier_exports.py:309
#: src/backend/verifier_exports.py:315 src/backend/verifier_exports.py:321
msgid "EXPORT_MEM_ERROR"
msgstr ""

#: src/backend/verifier_exports.py:316
msgid "PDF_FILE_NOT_FOUND"
msgstr ""

#: src/backend/verifier_exports.py:327
msgid "MEM_WS_INFO_WRONG"
msgstr ""

#: src/backend/controllers/splitter.py:450 src/backend/verifier_exports.py:333
msgid "MEM_WS_INFO_EMPTY"
msgstr ""

#: src/backend/classes/MEMWebServices.py:39
msgid "HOST_NOT_FOUND"
msgstr ""

#: src/backend/classes/SMTP.py:218
msgid "RESET_PASSWORD"
msgstr ""

#: src/backend/classes/SMTP.py:220
msgid "FORGOT_EMAIL_HEADER"
msgstr ""

#: src/backend/classes/SMTP.py:220
msgid "CLICK_HERE"
msgstr ""

#: src/backend/classes/SMTP.py:220
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""

#: src/backend/controllers/accounts.py:45 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:58 src/backend/models/accounts.py:84
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:85
#: src/backend/controllers/accounts.py:174
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:112
#: src/backend/controllers/accounts.py:205
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:137
#: src/backend/controllers/accounts.py:143
msgid "UPDATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:229
#: src/backend/controllers/accounts.py:235
#: src/backend/controllers/accounts.py:259
#: src/backend/controllers/accounts.py:265 src/backend/models/accounts.py:130
msgid "UPDATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:289 src/backend/models/accounts.py:150
msgid "CREATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:330
#: src/backend/controllers/accounts.py:336 src/backend/models/accounts.py:170
msgid "CREATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:337
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:357 src/backend/controllers/user.py:215
#: src/backend/controllers/user.py:244 src/backend/models/accounts.py:234
#: src/backend/models/accounts.py:257 src/backend/models/accounts.py:276
#: src/backend/models/user.py:209 src/backend/models/user.py:231
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:399
#: src/backend/controllers/accounts.py:405 src/backend/models/accounts.py:298
msgid "UPDATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:434
#: src/backend/controllers/accounts.py:440 src/backend/models/accounts.py:318
msgid "CREATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:441
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:455
#: src/backend/controllers/accounts.py:461 src/backend/models/accounts.py:340
msgid "DELETE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:476
#: src/backend/controllers/accounts.py:482 src/backend/models/accounts.py:192
msgid "DELETE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:504
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:79
#: src/backend/controllers/artificial_intelligence.py:392
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:103
msgid "CREATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:114
msgid "UPDATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:393
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/auth.py:65 src/backend/controllers/auth.py:215
#: src/backend/controllers/auth.py:254 src/backend/controllers/auth.py:262
#: src/backend/controllers/auth.py:265 src/backend/controllers/auth.py:267
msgid "JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:114
msgid "RESET_JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:147 src/backend/controllers/auth.py:194
#: src/backend/controllers/auth.py:239 src/backend/controllers/auth.py:286
#: src/backend/controllers/auth.py:297 src/backend/controllers/auth.py:307
#: src/backend/controllers/auth.py:334 src/backend/rest/auth.py:69
msgid "LOGIN_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:262
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""

#: src/backend/controllers/auth.py:298
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr ""

#: src/backend/controllers/auth.py:322
msgid "LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:323 src/backend/models/auth.py:140
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr ""

#: src/backend/controllers/auth.py:349
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:361
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:373
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:396 src/backend/controllers/auth.py:581
#: src/backend/controllers/auth.py:637 src/backend/controllers/auth.py:652
#: src/backend/controllers/auth.py:660 src/backend/controllers/auth.py:666
msgid "LDAP_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:397
msgid "LOGIN_LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:569 src/backend/controllers/auth.py:575
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:571 src/backend/controllers/auth.py:577
#: src/backend/controllers/auth.py:583 src/backend/controllers/auth.py:589
#: src/backend/controllers/auth.py:595
msgid "LDAP_SYNCHRO_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:587 src/backend/controllers/auth.py:593
#: src/backend/controllers/auth.py:672 src/backend/rest/auth.py:117
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr ""

#: src/backend/controllers/auth.py:635 src/backend/controllers/auth.py:650
#: src/backend/controllers/auth.py:658
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr ""

#: src/backend/controllers/auth.py:670 src/backend/rest/auth.py:115
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr ""

#: src/backend/controllers/config.py:61
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:77
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:93
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:109
msgid "RETRIEVE_REGEX_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:121 src/backend/controllers/config.py:141
#: src/backend/controllers/config.py:153 src/backend/controllers/config.py:173
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr ""

#: src/backend/controllers/config.py:122 src/backend/controllers/config.py:154
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr ""

#: src/backend/controllers/config.py:194 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr ""

#: src/backend/controllers/config.py:214 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr ""

#: src/backend/controllers/config.py:255 src/backend/controllers/config.py:265
#: src/backend/controllers/config.py:270
msgid "ERROR_UPDATING_IMAGE"
msgstr ""

#: src/backend/controllers/config.py:256 src/backend/controllers/config.py:266
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr ""

#: src/backend/controllers/config.py:271
msgid "CUSTOM_NOT_PRESENT"
msgstr ""

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:34
#: src/backend/controllers/doctypes.py:76 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:40 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:60
#: src/backend/controllers/doctypes.py:96
#: src/backend/controllers/doctypes.py:109
#: src/backend/controllers/doctypes.py:161
#: src/backend/controllers/doctypes.py:192
msgid "DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:128
msgid "BUNDLESEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:135
msgid "DOCUMENTSEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:154
msgid "DOCTYPESEPARATOR"
msgstr ""

#: src/backend/controllers/forms.py:71 src/backend/controllers/forms.py:97
#: src/backend/controllers/forms.py:214
msgid "FORMS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:112 src/backend/controllers/forms.py:161
#: src/backend/models/forms.py:63
msgid "GET_FORM_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:144
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:208 src/backend/controllers/forms.py:336
#: src/backend/controllers/forms.py:342
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:228 src/backend/controllers/forms.py:234
msgid "DELETE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:243 src/backend/controllers/inputs.py:107
#: src/backend/controllers/outputs.py:58
#: src/backend/controllers/positions_masks.py:160
msgid "COPY_OF"
msgstr ""

#: src/backend/controllers/forms.py:260 src/backend/controllers/forms.py:266
msgid "DUPLICATE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:280 src/backend/controllers/forms.py:286
msgid "DISABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:300 src/backend/controllers/forms.py:306
msgid "ENABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:322
msgid "GET_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:75 src/backend/controllers/inputs.py:135
#: src/backend/controllers/inputs.py:162 src/backend/controllers/inputs.py:173
#: src/backend/controllers/inputs.py:186
msgid "CREATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:76 src/backend/controllers/inputs.py:136
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr ""

#: src/backend/controllers/inputs.py:89 src/backend/controllers/inputs.py:95
msgid "UPDATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:120 src/backend/controllers/inputs.py:126
msgid "DUPLICATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:163
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:174
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:199
msgid "GET_INPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:212
msgid "GET_INPUT_BY_INPUT_ID_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:233 src/backend/controllers/inputs.py:239
msgid "DELETE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:275
msgid "FS_WATCHER_DELETION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:276 src/backend/controllers/inputs.py:343
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr ""

#: src/backend/controllers/inputs.py:322 src/backend/controllers/inputs.py:342
msgid "FS_WATCHER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:323
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:348
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:354
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/mailcollect.py:36
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:52
msgid "UPDATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:68
msgid "CREATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:82
#: src/backend/controllers/mailcollect.py:88
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:102
#: src/backend/controllers/mailcollect.py:108
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:122
#: src/backend/controllers/mailcollect.py:128
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:142
#: src/backend/controllers/mailcollect.py:152
msgid "MAILCOLLECT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:65 src/backend/controllers/outputs.py:71
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:100
#: src/backend/controllers/outputs.py:122
#: src/backend/controllers/outputs.py:128
msgid "UPDATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:101
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr ""

#: src/backend/controllers/outputs.py:152
msgid "CREATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:165
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:178
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:192
#: src/backend/controllers/outputs.py:198
msgid "DELETE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:42
#: src/backend/controllers/positions_masks.py:66
#: src/backend/controllers/positions_masks.py:125
#: src/backend/controllers/positions_masks.py:131
msgid "POSITION_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:81
#: src/backend/controllers/positions_masks.py:98
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:145
#: src/backend/controllers/positions_masks.py:151
msgid "DELETE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:176
#: src/backend/controllers/positions_masks.py:182
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:196
#: src/backend/controllers/positions_masks.py:202
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:216
#: src/backend/controllers/positions_masks.py:222
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:245
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:268
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:286
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:304
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/privileges.py:37
#: src/backend/controllers/privileges.py:65
msgid "GET_PRIVILEGES_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:47 src/backend/controllers/roles.py:53
#: src/backend/controllers/roles.py:95 src/backend/controllers/roles.py:101
#: src/backend/models/roles.py:84
msgid "UPDATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:75 src/backend/models/roles.py:104
msgid "CREATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:114
msgid "GET_ROLE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:128 src/backend/controllers/roles.py:134
msgid "DELETE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:148 src/backend/controllers/roles.py:154
msgid "DISABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:168 src/backend/controllers/roles.py:174
msgid "ENABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:91
msgid "LOAD_METADATA_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:137
#: src/backend/controllers/verifier.py:75
msgid "AT"
msgstr ""

#: src/backend/controllers/splitter.py:161
msgid "FORM_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:164
msgid "CUSTOMER_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:232
msgid "BATCH_NOT_FOUND"
msgstr ""

#: src/backend/controllers/splitter.py:233
msgid "BATCH_ID_NOT_FOUND"
msgstr ""

#: src/backend/controllers/splitter.py:242
#: src/backend/controllers/verifier.py:591
msgid "UPDATE_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:277
#: src/backend/controllers/verifier.py:348
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:387
msgid "ADD_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:522
#: src/backend/controllers/splitter.py:784
msgid "EXPORT_PDF_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:544
#: src/backend/controllers/splitter.py:809
msgid "EXPORT_XML_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:560
msgid "UPDATE_BATCH_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:573
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:586
msgid "UPDATE_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:601
#: src/backend/controllers/splitter.py:622
#: src/backend/controllers/splitter.py:637
#: src/backend/controllers/splitter.py:652
msgid "UPDATE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:666
msgid "CMIS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:679
msgid "OPENADS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:859
msgid "CHECK_FOLDER_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:860
msgid "FOLDER_DOES_NOT_EXIST"
msgstr ""

#: src/backend/controllers/splitter.py:877
msgid "OPENADS_ADD_DOC_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:971
#: src/backend/controllers/verifier.py:578 src/backend/models/splitter.py:566
#: src/backend/models/verifier.py:171
msgid "GET_TOTALS_ERROR"
msgstr ""

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/tasks_watcher.py:34
msgid "CREATE_TASK_ERROR"
msgstr ""

#: src/backend/controllers/user.py:64
msgid "CREATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:103 src/backend/controllers/user.py:120
#: src/backend/controllers/user.py:186 src/backend/models/user.py:139
#: src/backend/models/user.py:186
msgid "GET_USER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/user.py:137
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr ""

#: src/backend/controllers/user.py:160
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr ""

#: src/backend/controllers/user.py:180 src/backend/controllers/user.py:185
msgid "RESET_PASSWORD_ERROR"
msgstr ""

#: src/backend/controllers/user.py:181
msgid "RESET_TOKEN_MISMATCH"
msgstr ""

#: src/backend/controllers/user.py:265
msgid "UPDATE_PROFILE"
msgstr ""

#: src/backend/controllers/user.py:266
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:272
msgid "UPDATE_USER"
msgstr ""

#: src/backend/controllers/user.py:273
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:300 src/backend/controllers/user.py:306
#: src/backend/models/user.py:254 src/backend/models/user.py:320
msgid "UPDATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:320 src/backend/controllers/user.py:326
msgid "DELETE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:340 src/backend/controllers/user.py:346
msgid "DISABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:360 src/backend/controllers/user.py:366
msgid "ENABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:383 src/backend/controllers/user.py:389
#: src/backend/models/user.py:276
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:404 src/backend/controllers/user.py:411
#: src/backend/models/user.py:298
msgid "UPDATE_FORMS_USER_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:40
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:170
#: src/backend/controllers/verifier.py:272
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:193
#: src/backend/controllers/verifier.py:290
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:216
#: src/backend/controllers/verifier.py:234
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:304
#: src/backend/controllers/verifier.py:310
msgid "DELETE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:325
#: src/backend/controllers/verifier.py:331
msgid "UPDATE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:478
#: src/backend/controllers/verifier.py:481
#: src/backend/controllers/verifier.py:498
#: src/backend/controllers/verifier.py:521
#: src/backend/controllers/verifier.py:522
msgid "API_INSEE_ERROR_CONNEXION"
msgstr ""

#: src/backend/controllers/verifier.py:550
msgid "VAT_NOT_VALID"
msgstr ""

#: src/backend/controllers/verifier.py:555
#: src/backend/controllers/verifier.py:556
msgid "VAT_API_ERROR"
msgstr ""

#: src/backend/models/accounts.py:108
msgid "SUPPLIER_UPDATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr ""

#: src/backend/models/auth.py:43 src/backend/models/auth.py:101
#: src/backend/models/user.py:43 src/backend/rest/auth.py:70
msgid "BAD_USERNAME"
msgstr ""

#: src/backend/models/auth.py:45 src/backend/models/user.py:45
msgid "BAD_PASSWORD"
msgstr ""

#: src/backend/models/auth.py:47
msgid "USER_DELETED"
msgstr ""

#: src/backend/models/auth.py:49
msgid "USER_DISABLED"
msgstr ""

#: src/backend/models/auth.py:70 src/backend/models/auth.py:80
#: src/backend/models/roles.py:60
msgid "ROLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/auth.py:165
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/models/auth.py:211
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/auth.py:233
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:55
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:58
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr ""

#: src/backend/models/custom_fields.py:106
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:129
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr ""

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/forms.py:86
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/forms.py:109
msgid "GET_DEFAULT_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:133
msgid "UPDATE_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:155
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/forms.py:211
msgid "ADD_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:214
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/inputs.py:60 src/backend/models/inputs.py:83
msgid "INPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/inputs.py:125
msgid "INPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/inputs.py:145
msgid "INPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/mailcollect.py:85
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:101
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr ""

#: src/backend/models/roles.py:126
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr ""

#: src/backend/models/roles.py:148
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:238
msgid "GET_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:260 src/backend/models/splitter.py:283
msgid "GET_PAGES_ERROR"
msgstr ""

#: src/backend/models/splitter.py:305
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:328
msgid "GET_DOCUMENT_ERROR"
msgstr ""

#: src/backend/models/splitter.py:350
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr ""

#: src/backend/models/tasks_watcher.py:89
msgid "UPDATE_TASK_ERROR"
msgstr ""

#: src/backend/models/user.py:47
msgid "USER"
msgstr ""

#: src/backend/models/user.py:47
msgid "ALREADY_REGISTERED"
msgstr ""

#: src/backend/models/user.py:162
msgid "GET_USER_BY_MAIL_ERROR"
msgstr ""

#: src/backend/models/verifier.py:104 src/backend/models/verifier.py:125
msgid "INVOICE_UPDATE_ERROR"
msgstr ""

#: src/backend/rest/auth.py:45 src/backend/rest/auth.py:74
msgid "PGSQL_ERROR"
msgstr ""

#: src/backend/rest/auth.py:140 src/backend/rest/auth.py:168
#: src/backend/rest/auth.py:183
msgid "REQUEST_MODIFS_ERROR"
msgstr ""

#: src/backend/rest/auth.py:153
msgid "RETRIEVE_LOGIN_METHODS_ERROR"
msgstr ""

#: src/backend/rest/splitter.py:42 src/backend/rest/verifier.py:40
msgid "UNKNOW_ERROR"
msgstr ""

